use crate::payloader::prelude::*;

#[repr(u16)]
#[derive(Debug, Clone, PartialEq, Eq, TryFromPrimitive, EnumIter, EnumString, strum_macros::Display, IntoPrimitive)]
pub enum ProgramIdOven {
    NoProgram = 0,
    DefrostBottom = 1,
    AutoHotAir = 2,
    AutoTopBottomHeat = 3,
    EcoHotAir1 = 4,
    EcoHotAir2 = 5,
    EcoHotAir = 6,
    RoastAutomatic = 7,
    UniversalCook = 8,
    Grill = 9,
    GrillLarge = 10,
    GrillSmall = 11,
    Descale = 12,
    HotAirPlus = 13,
    IntenseBaking = 14,
    ComboCookGrill = 15,
    ComboCookHotAirPlus = 16,
    ComboCookTopBottom = 17,
    CakeSpecial = 18,
    Microwave = 19,
    MicrowaveRoastAutomatic = 20,
    MicrowaveGrill = 21,
    MicrowaveHotAirPlus = 22,
    MicrowaveFanGrill = 23,
    TopBottomHeat = 24,
    TopHeat = 25,
    Pyrolysis = 26,
    RapidHeat = 27,
    Rinse = 28,
    FanGrill = 29,
    EcoHotAir3 = 30,
    BottomHeat = 31,
    KeepWarm = 32,
    DefrostSteam = 33,
    DefrostMicrowave = 34,
    ClimateRoastAutomatic = 35,
    ConvectionBake = 36,
    ConvectionRoast = 37,
    MicrowaveConvectionBake = 38,
    MicrowaveConvectionRoast = 39,
    ClimateHotAirPlus = 40,
    HeatBottom = 41,
    HeatSteam = 42,
    HeatMicrowave = 43,
    CookFish = 44,
    CookMeat = 45,
    CookVegetables = 46,
    ClimateConvectionBake = 47,
    ClimateRoast = 48,
    ClimateHotAirPlus2 = 49,
    ClimateIntenseBaking = 50,
    ClimateTopBottomHeat = 51,
    ClimateConvectionRoast = 52,
    Popcorn = 53,
    QuickMicrowave = 54,
    RoastAutomaticRf = 55,
    ConvectionBakeRf = 56,
    GrillRf = 57,
    HotAirPlusRf = 58,
    IntenseBakingRf = 59,
    TopBottomHeatRf = 60,
    TopHeatRf = 61,
    FanGrillRf = 62,
    BottomHeatRf = 63,
    ConvectionRoastRf = 64,
    SteamHeat = 65,
    SteamHold = 66,
    SteamAltitudeAdjust = 67,
    DescaleSoak = 68,
    DescaleRinse = 69,
    SteamResidualWater = 70,
    Rotisserie = 71,
    SousVide = 72,
    SteamDry = 73,
    ClimateIntenseBaking2 = 74,
    EcoUniversalCook = 75,
    ClimateTopBottomHeat2 = 76,
    ComboCookMicrowave = 77,
    RotisserieLarge = 78,
    RotisserieSmall = 79,
    RotisserieFan = 80,
    AutoRoastAutomatic = 81,
    AutoIntenseBaking = 82,
    AutoBottomHeat = 83,
    AutoTopHeat = 84,
    SabbathTopBottom = 85,
    SabbathBottomHeat = 86,
    AutoSteamCook = 87,
    HydrocleanBottomHeat = 88,
    SoloRf = 89,
    HydrocleanTopBottomHeat = 90,
    HydrocleanUniversalCook = 91,
    DryHotAirPlusWithSteam = 92,
    DrySteamOnly = 93,
    DryGrillWithSteam = 94,
}

crate::impl_tryfrom_wrapper!(ProgramIdOven, E16);

#[repr(u8)]
#[derive(Debug, Clone, PartialEq, Eq, TryFromPrimitive, EnumIter, EnumString, strum_macros::Display, IntoPrimitive)]
pub enum SelectionType {
    InitialAsConfigured = 0,
    InitialDefault = 1,
    Parametrized = 2,
    Deselect = 3,
    InitialFull = 4,
    InitialAsConfiguredViaSyndication = 10,
    InitialDefaultViaSyndication = 11,
    ParametrizedTemperature = 12,
    Last = 13,
}

crate::impl_tryfrom_wrapper!(SelectionType, E8);

