use crate::payloader::prelude::*;

/// GLOBAL_EnumMieleDeviceId - Miele device type identifiers
#[repr(u8)]
#[derive(Debug, Clone, TryFromPrimitive, IntoPrimitive, PartialEq, Eq, EnumIter, EnumString, strum_macros::Display)]
pub enum MieleDeviceId {
    NoUse = 0,
    WashingMachine = 1,
    TumbleDryer = 2,
    WashingMachineSemiProfessional = 3,
    TumbleDryerSemiProfessional = 4,
    WashingMachineProfessional = 5,
    TumbleDryerProfessional = 6,
    Dishwasher = 7,
    DishwasherSemiProfessional = 8,
    DishwasherProfessional = 9,
    Cooker = 10,
    CookerMicrowave = 11,
    Oven = 12,
    OvenMicrowave = 13,
    HobHighlight = 14,
    SteamOven = 15,
    Microwave = 16,
    CoffeeSystem = 17,
    Hood = 18,
    Fridge = 19,
    Freezer = 20,
    FridgeFreezerCombi = 21,
    ChestFreezer = 22,
    RobotVacuumCleaner = 23,
    WasherDryer = 24,
    WarmingDrawer = 25,
    BeverageMaker = 26,
    HobInduction = 27,
    HobGas = 28,
    HobHighlightInductionCombi = 29,
    HobHighlightGasCombi = 30,
    SteamOvenCombi = 31,
    WineCabinet = 32,
    WineConditioningUnit = 33,
    WineStorageConditioningUnit = 34,
    WaterDispenser = 35,
    IceMaker = 36,
    IceCrusher = 37,
    CellarCompartment = 38,
    OvenDouble = 39,
    SteamOvenDouble = 40,
    SteamOvenDoubleCombi = 41,
    MicrowaveDouble = 42,
    OvenMicrowaveDoubleCombi = 43,
    WasherDisinfector = 44,
    SteamOvenMicrowaveCombi = 45,
    RemoteControl = 46,
    VoiceControl = 47,
    VacuumDrawer = 48,
    WashingMachineSemiProfessionalDeprecated = 51,
    TumbleDryerSemiProfessionalDeprecated = 52,
    WashingMachineProfessionalDeprecated = 53,
    TumbleDryerProfessionalDeprecated = 54,
    WasherDisinfectorLaboratory = 60,
    WasherDisinfectorMedical = 61,
    EndoThermalDisinfector = 62,
    TableTopSterilizer = 63,
    SteamLargeSterilizer = 64,
    ContainerTrolleyWasher = 65,
    SteamLargeDisinfector = 66,
    DeviceIdVerticalFarm = 71,
    DeviceIdVacuumCleaner = 72,
    DeviceIdVacuumCleanerCleaningStation = 75,
    DeviceIdVarioCool = 76,
    DeviceIdCooling = 77,
    DeviceIdGrillUnit = 78,
    DeviceIdLaundryCareCabinet = 79,
    DeviceTypeSteelcoCleanDisinfectionMachine = 80,
    DeviceIdC2CSterilizer = 81,
    DeviceIdC2CReserved2 = 82,
    DeviceIdC2CReserved3 = 83,
    DeviceIdC2CReserved4 = 84,
    DeviceIdC2CReserved5 = 85,
    DeviceTypeSteelcoReserved1 = 86,
    DeviceTypeSteelcoReserved2 = 87,
    DeviceTypeSteelcoReserved3 = 88,
    DeviceTypeSteelcoReserved4 = 89,
    DeviceTypeSteelcoReserved5 = 90,
    DeviceTypeMax = 91,
    DeviceTypeInvalid = 255,
}

crate::impl_tryfrom_wrapper!(MieleDeviceId, E8);

