pub use dop2marshal::AssocTypes;
pub use crate::{impl_tryfrom_dop2struct, Dop2Payloads};
pub use crate::{DopArray, TaggedDopField, Dop2Struct, Dop2PayloadsKind};
pub use crate::{E8, E16};
pub use strum_macros::{EnumIter, EnumString};
pub use num_enum::{TryFromPrimitive, IntoPrimitive};

#[macro_use]
pub use crate::macros;

#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, TryFromPrimitive, EnumIter, EnumString, strum_macros::Display, IntoPrimitive)]
pub enum ValueInterpretation {
    None = 0,
    Percentage = 1,
    TemperatureC1 = 2,
    TemperatureC100 = 3,
    TemperatureF100 = 4,
    DurationSec = 5,
    DurationMin = 6,
    Step = 7,
    WeightGram = 8,
    Numerical = 9,
    Date = 10,
    MicrowavePowerSteps = 11,
    RfPower = 12,
    RfEnergy = 13,
    RfMode = 14,
    Browning = 15,
    DegreeOfCooking = 16,
    TimeFormat = 17,
    TimePresentation = 18,
    Language = 19,
    BurstOfSteam = 20,
    DisplayScheme = 21,
    DisplayInStandby = 22,
    Lighting = 23,
    TemperatureUnit = 24,
    WeightUnit = 25,
    StartScreen = 26,
    WaterHardness = 27,
    TestState = 28,
    TimeUtc = 29,
    VoltageAndFrequency = 30,
    StartPoint = 31,
    EndPoint = 32,
    ParameterShape = 33,
    StartPointOrRightNow = 34,
    WaterLevelMmws = 35,
    WaterInletWay = 36,
    DrumSpeedRpm = 37,
    OnOff = 38,
    DoorSwitch = 39,
    DoorLockSwitch = 40,
    WpsSwitch = 41,
    TwindosContainer1Switch = 42,
    TwindosContainer2Switch = 43,
    EcoWaterLiter = 44,
    EcoEnergyKwh = 45,
    EcoEnergyWatt = 46,
    StartPointOnlyRightNow = 47,
    TemperatureF1 = 48,
    DrumSpeed10Rpm = 49,
    OperationMode = 50,
    Name = 51,
    TimeBackground = 52,
    DisplayBrightness = 53,
    DisplayContrast = 54,
    VolumeSignalTonesLevel = 55,
    VolumeKeyTone = 56,
    MotoePosition = 57,
    DoorExtOpeningEnabled = 58,
    WawPosition = 59,
    WawDirection = 60,
    CookingShelfs3 = 80,
    CookingShelfs4 = 81,
    CookingShelfs5 = 82,
    CookingShelfs6 = 83,
    PerformanceMode = 90,
    Altitude = 91,
    ProfileChange = 92,
    MicrowavePower = 96,
    Variant = 97,
    SensorGroup = 98,
    TimerDayOfWeekAssignment = 99,
    TimeUtc0 = 100,
    ActiveUser = 101,
    TemperatureText = 102,
    WeightTenthOfGram = 103,
    TimeDisplay = 104,
    DeviceHeight = 105,
    DeviceWidth = 106,
    AutoDosCartridgeType = 107,
    RinseAidCapacityMl = 108,
    Knock2Open = 109,
    CountryVariant = 110,
    NetworkingCountry = 111,
    CountryLanguage = 112,
    Lbs = 120,
    EnergyWh = 121,
    CoolAirBlowersFollowUp = 122,
    CookingProgramId = 123,
    Extend = 124,
    ApproximationLightOption = 125,
    BurstsOfSteamType = 126,
    Lbs100 = 127,
    DurationSecOrUndefined = 128,
    WaterHardnessDh = 129,
    FlowMlMin = 130,
    TimeIn100Ms = 131,
    Concentration = 132,
    WaterSource = 133,
    TempCalibration = 134,
    FoodProbeSelection = 135,
    FoodProbeSerialNumber = 136,
    LiquidQuantityLiters = 137,
    LiquidQuantity100Milliliters = 138,
    LiquidQuantityMilliliters = 139,
    Day = 140,
    Program = 141,
    SpinSpeed10RpmText = 142,
    Percent10 = 143,
    Temperature10C = 144,
    LiquidQuantity500Milliliters = 145,
    Percent100 = 146,
    Temperature10F = 147,
    Quantity10Liters = 148,
    MicroSiemens10PerCm = 149,
    MicroSiemensPerCm = 150,
}

crate::impl_tryfrom_wrapper!(ValueInterpretation, E8);

